@startuml

actor player

activate player
player->client:readyToPlay
activate client

client->server:readyToPlay

opt is player signed up
  activate server
  server->server:updatePlayersList
  server->server:appendToChat("player is ready")
  server->client:ack
  client-->player:serverAck
else
  server-->client:error(msg)
  client-->player:error(msg)
  deactivate server
  deactivate client
  deactivate player
end

@enduml
