/*
 * The MIT License
 *
 * Copyright 2019 Matan Davidi.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package samt.scribble.client;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.InetAddress;
import javax.swing.JOptionPane;
import samt.scribble.DefaultScribbleParameters;
import samt.scribble.communication.Commands;
import samt.scribble.communication.DatagramListener;
import samt.scribble.communication.GroupConnection;
import samt.scribble.communication.ListeningThread;
import samt.scribble.communication.MessageSender;
import samt.scribble.communication.messages.JoinMessage;

/**
 * La classe LoginPanel è una sottoclasse di JPanel e contiene i componenti
 * utili per accedere al server.
 *
 * @author Matan Davidi
 * @version 1.0 (2019-05-04 - 2019-05-04)
 */
public class LoginPanel extends javax.swing.JPanel implements DatagramListener {

    private LoginListener listener;

    private String username;

    private ListeningThread listeningThread;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        listener = null;
    }

    public void setListener(LoginListener listener) {
        this.listener = listener;
    }

    public void unsetListener(LoginListener listener) {
        this.listener = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamePanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(2, 1));

        usernamePanel.setLayout(new java.awt.GridLayout());

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Inserisci il tuo nome utente:");
        usernamePanel.add(usernameLabel);
        usernamePanel.add(usernameTextField);

        add(usernamePanel);

        loginButton.setText("Accedi");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        add(loginButton);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        String username = usernameTextField.getText();

        if (!username.isEmpty()) {

            JoinMessage joinMessage = new JoinMessage(username);
            this.username = username;

            try {

                MessageSender.sendMessage(InetAddress.getByName("127.0.0.1"), DefaultScribbleParameters.DEFAULT_SERVER_PORT, joinMessage);
                listeningThread = new ListeningThread(DefaultScribbleParameters.DEFAULT_CLIENT_PORT);
                listeningThread.addDatagramListener(this);
                listeningThread.start();

            } catch (IOException ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage());

            }

        } else {

            JOptionPane.showMessageDialog(this, "Inserire un nome utente all'interno del relativo campo.");

        }
    }//GEN-LAST:event_loginButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JPanel usernamePanel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void messageReceived(DatagramPacket datagramPacket) {

        byte[] packetData = datagramPacket.getData();

        if (packetData.length > 0) {

            byte[] messageBytes = new byte[packetData.length - 1];

            for (int i = 1; i < packetData.length; ++i) {

                messageBytes[i - 1] = packetData[i];

            }

            if (packetData[0] == Commands.USERS_LIST) {

                try {

                    GroupConnection groupConnection = new GroupConnection(InetAddress.getByAddress(messageBytes), DefaultScribbleParameters.DEFAULT_GROUP_PORT);

                    if (username != null && listener != null) {

                        listener.loggedIn(username, groupConnection);

                    }

                } catch (IOException ex) {

                    JOptionPane.showMessageDialog(this, ex.getMessage());

                }

            }

            JOptionPane.showMessageDialog(this, messageString);

        }

    }
}
