/'
 ' Scribble, the player disconnects from a game in progress.
 '
 ' @author Mattia Ruberto
 ' @author Gabriele Alessi
 ' @version 19.03.2019
 '/

@startuml playerDisconnected

actor user

user->client:disconnection request
activate client

client->server:leave(nickname, ip, port)
activate server

opt successful disconnection
    server->server:removePlayer(nickname, ip)
    server->client:removed()
    server->server:updateChat(LEAVED, nickname)
    client->user:OK
else
    server->client:error(msg)
    client->user:error(msg)
end

@enduml