/**
 * Il form della chat.
 * @author Mattia Lazzaroni
 * @version 20.02.2019
 */
public class ChatForm extends javax.swing.JFrame implements MessageListener{

    /**
     * Il client che comunica.
     */
    private MulticastClient messageClient;
    
    /**
     * Creates new form ChatForm
     */
    public ChatForm() {
        initComponents();
        messageClient = new MulticastClient(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NicknamePanel = new javax.swing.JPanel();
        NicknameLabel = new javax.swing.JLabel();
        NicknameTextField = new javax.swing.JTextField();
        MessagePanel = new javax.swing.JPanel();
        MessageLabel = new javax.swing.JLabel();
        MessageTextArea = new javax.swing.JTextArea();
        SendPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        SendButton = new javax.swing.JButton();
        ChatPanel = new javax.swing.JPanel();
        ChatScrollPanel = new javax.swing.JScrollPane();
        ChatTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(0, 5));

        NicknamePanel.setPreferredSize(new java.awt.Dimension(60, 60));
        NicknamePanel.setLayout(new java.awt.GridLayout(1, 2));

        NicknameLabel.setText("Nickname:");
        NicknamePanel.add(NicknameLabel);
        NicknamePanel.add(NicknameTextField);

        getContentPane().add(NicknamePanel, java.awt.BorderLayout.PAGE_START);

        MessagePanel.setPreferredSize(new java.awt.Dimension(20, 20));
        MessagePanel.setLayout(new java.awt.GridLayout(2, 0));

        MessageLabel.setText("Message:");
        MessagePanel.add(MessageLabel);

        MessageTextArea.setColumns(20);
        MessageTextArea.setRows(5);
        MessagePanel.add(MessageTextArea);

        getContentPane().add(MessagePanel, java.awt.BorderLayout.CENTER);

        SendPanel.setPreferredSize(new java.awt.Dimension(175, 175));
        SendPanel.setLayout(new java.awt.GridLayout(2, 1));

        ButtonPanel.setLayout(new java.awt.GridLayout(1, 0));

        SendButton.setText("Send");
        SendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendButtonMouseClicked(evt);
            }
        });
        ButtonPanel.add(SendButton);

        SendPanel.add(ButtonPanel);

        ChatPanel.setLayout(new java.awt.GridLayout(1, 0));

        ChatTextArea.setColumns(20);
        ChatTextArea.setRows(5);
        ChatScrollPanel.setViewportView(ChatTextArea);

        ChatPanel.add(ChatScrollPanel);

        SendPanel.add(ChatPanel);

        getContentPane().add(SendPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento che si scatena al click del mouse sul bottone.
     * @param evt L'evento del bottone cliccato.
     */
    private void SendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendButtonMouseClicked
        String nickname = NicknameTextField.getText()+": ";
        String message = nickname+MessageTextArea.getText();
        
        MessageTextArea.setText("");
        
        messageClient.setInfo(message);
        messageClient.sendMessage();
    }//GEN-LAST:event_SendButtonMouseClicked

    /**
     * Evento che si scatena quando vengono chiamati i componenti del form.
     * @param evt L'evento del form caricato.
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        messageClient.start();
    }//GEN-LAST:event_formComponentShown

    /**
     * Main in cui testare gli argomenti da linea di comando.
     * @param args Gli argomenti da linea di comando.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChatForm cf = new ChatForm();
                cf.setVisible(true);
                cf.setSize(400, 400);
                cf.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JScrollPane ChatScrollPanel;
    private javax.swing.JTextArea ChatTextArea;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JPanel MessagePanel;
    private javax.swing.JTextArea MessageTextArea;
    private javax.swing.JLabel NicknameLabel;
    private javax.swing.JPanel NicknamePanel;
    private javax.swing.JTextField NicknameTextField;
    private javax.swing.JButton SendButton;
    private javax.swing.JPanel SendPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void messageReceived() {
        ChatTextArea.append(messageClient.getMessageReceived());
        ChatTextArea.append("\n");
    }
}