@startuml

actor Player as p
participant Client as c
participant Server as s

activate s
s --> s: pickWord
s --> s: pickSketcher

activate c
s --> c: sketcher(player, word)

activate p
opt is player guesser
  loop while word not guessed
    p --> c: guess(word)
    c --> s: guess(word)
    opt is word right
      s --> s: updatePlayerScore(player, time)
      s --> c: wordGuessed(player, word, score)
      c --> c: disableChat
      c --> p: wordGuessed(word, score)
    else
      s --> c: wrongWord(word)
    end
  end
else
  loop while word not guessed
    p --> c: draw
    c --> s: sendDrawing(drawing)
    s --> c: sendDrawing(drawing)
    c --> p: drawDrawing(drawing)
  end
end

deactivate c
deactivate s
deactivate p

@enduml
